# Generated by Django 4.1.7 on 2023-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_country', models.CharField(max_length=100)),
                ('loading_po_code', models.CharField(max_length=100)),
                ('requested_loading_date', models.DateField()),
                ('delivery_country', models.CharField(max_length=100)),
                ('delivery_po_code', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('ftl_ltl', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('pic_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
